/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/Ear.gltf -o src/components/Ear.jsx -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ear(props) {
  const { nodes, materials } = useGLTF('/Ear.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cushion.geometry} material={materials.Cushion} />
      <mesh geometry={nodes.Ear_Cup.geometry} material={materials['Black-1']} />
      <mesh geometry={nodes['Mid-'].geometry} material={materials['Black-2']} />
      <mesh geometry={nodes.Seprator.geometry} material={materials.Connector} />
      <mesh geometry={nodes.Seprator001.geometry} material={materials['Black-1']} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials['Black-1']} />
      <mesh geometry={nodes.Cylinder025_1.geometry} material={materials.GlowBlue} />
    </group>
  )
}

useGLTF.preload('/Ear.gltf')
